apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: argo-scaffolder
  title: Argo Scaffolder
  description: Add Backstage Integration up to ArgoCD for Existing Repo
spec:
  owner: platform-team
  type: service
  
  parameters:
    - title: Fill in some steps
      required:
        - repoUrl
        - new_component_name
      properties:
        repoUrl:
          title: Repository URL
          type: string
          description: Provide a repo url
        new_component_name:
          title: Name
          type: string
          description: The name for the Template created by this
  steps:
    - id: fetch
      name: Copy Files
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{parameters.new_component_name}}
    - id: debug
      action: debug:log
      input:
        message: ${{ parameters.repoUrl }}
    - id: pr
      name: Create PR
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        branchName: backstage/add-files
        title: Add Backstage files
        description: Add Backstage catalog metadata and template files
        sourcePath: .
